[package]
authors = ["Demir Yerli <mrquantumoff@protonmail.com>"]
build = "build.rs"
edition = "2021"
name = "mcmodpackmanager-lite"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
open = "5.0.0"
slint = {version = "1.1", features = ["backend-winit", "renderer-winit-software", "renderer-winit-femtovg", "std", "compat-1-0"], default-features = false}
tokio = {version = "1", features = ["full"]}

[build-dependencies]
slint-build = "1.1"
